/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import control.btnIntface;
import myMqtt.MqttSubscriber;

/**
 *
 * @author winkste
 */
public class homeAreaPanelEG extends javax.swing.JPanel {

    /**
     * Creates new form homeTempPanel
     */
    public homeAreaPanelEG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        carport_sjl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kitchen_sjl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        livRoom_sjl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hall_sjl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        guestWc_sjl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        outside_sjl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home/erdgeschoss.jpeg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(595, 333));
        jPanel1.setMinimumSize(new java.awt.Dimension(595, 333));
        jPanel1.setName(""); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(595, 333));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Carport");

        carport_sjl.setBackground(new java.awt.Color(255, 255, 255));
        carport_sjl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        carport_sjl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        carport_sjl.setText("(+12°C/10%)");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Esszimmer");

        kitchen_sjl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        kitchen_sjl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kitchen_sjl.setText("(+12°C/40%)");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Wohnzimmer");

        livRoom_sjl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        livRoom_sjl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        livRoom_sjl.setText("(+12°C/40%)");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Flur");

        hall_sjl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        hall_sjl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hall_sjl.setText("(+12°C/40%)");

        jLabel6.setBackground(new java.awt.Color(51, 51, 255));
        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gäste WC");

        guestWc_sjl.setBackground(new java.awt.Color(51, 51, 255));
        guestWc_sjl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        guestWc_sjl.setForeground(new java.awt.Color(255, 255, 255));
        guestWc_sjl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guestWc_sjl.setText("(+12°C/40%)");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Außen");

        outside_sjl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        outside_sjl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outside_sjl.setText("(-05°C/40%)");
        outside_sjl.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(650, 650, 650)
                        .addComponent(carport_sjl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(kitchen_sjl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(hall_sjl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(650, 650, 650)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(660, 660, 660)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(660, 660, 660)
                        .addComponent(outside_sjl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(guestWc_sjl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(livRoom_sjl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(carport_sjl)
                        .addGap(84, 84, 84)
                        .addComponent(kitchen_sjl)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(hall_sjl)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(outside_sjl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(guestWc_sjl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(livRoom_sjl)))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(4, 4, 4)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carport_sjl;
    private javax.swing.JLabel guestWc_sjl;
    private javax.swing.JLabel hall_sjl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kitchen_sjl;
    private javax.swing.JLabel livRoom_sjl;
    private javax.swing.JLabel outside_sjl;
    // End of variables declaration//GEN-END:variables
    String carportTemp_str = "-07.00°C";
    String carportHum_str = "50.0%";    
    String livingTemp_str = "-07.00°C";
    String livingHum_str = "50.0%";
    String hallTemp_str = "-07.00°C";
    String hallHum_str = "50.0%";
    String kitchenTemp_str = "-07.00°C";
    String kitchenHum_str = "50.0%";
    
    public MqttSubscriber getMqttSubscriberCarportTemperature(String filter) {
        return(new MqttSubscriber(){
            @Override
            public String getFilter() {
                return(filter);
            }

            @Override
            public void notify(String msg) {
                carportTemp_str = msg + "°C";
                carport_sjl.setText("(" + carportTemp_str + "/" + carportHum_str + ")");
            }
        });
    }
    
    public MqttSubscriber getMqttSubscriberCarportHumidity(String filter) {
        return(new MqttSubscriber(){
            @Override
            public String getFilter() {
                return(filter);
            }

            @Override
            public void notify(String msg) {
                carportHum_str = msg + "°C";
                carport_sjl.setText("(" + carportTemp_str + "/" + carportHum_str + ")");
            }
        });
    }
    
    
    public MqttSubscriber getMqttSubscriberLivingTemperature(String filter) {
        return(new MqttSubscriber(){
            @Override
            public String getFilter() {
                return(filter);
            }

            @Override
            public void notify(String msg) {
                livingTemp_str = msg + "°C";
                livRoom_sjl.setText("(" + livingTemp_str + "/" + livingHum_str + ")");
            }
        });
    }
    
    public MqttSubscriber getMqttSubscriberLivingHumidity(String filter) {
        return(new MqttSubscriber(){
            @Override
            public String getFilter() {
                return(filter);
            }

            @Override
            public void notify(String msg) {
                livingHum_str = msg + "°C";
                livRoom_sjl.setText("(" + livingTemp_str + "/" + livingHum_str + ")");
            }
        });
    }
    
    
    public MqttSubscriber getMqttSubscriberHallTemperature(String filter) {
        return(new MqttSubscriber(){
            @Override
            public String getFilter() {
                return(filter);
            }

            @Override
            public void notify(String msg) {
                hallTemp_str = msg + "°C";
                hall_sjl.setText("(" + hallTemp_str + "/" + hallHum_str + ")");
            }
        });
    }
    
    public MqttSubscriber getMqttSubscriberHallHumidity(String filter) {
        return(new MqttSubscriber(){
            @Override
            public String getFilter() {
                return(filter);
            }

            @Override
            public void notify(String msg) {
                hallHum_str = msg + "°C";
                hall_sjl.setText("(" + hallTemp_str + "/" + hallHum_str + ")");
            }
        });
    }
    
    public MqttSubscriber getMqttSubscriberKitchenTemperature(String filter) {
        return(new MqttSubscriber(){
            @Override
            public String getFilter() {
                return(filter);
            }

            @Override
            public void notify(String msg) {
                kitchenTemp_str = msg + "°C";
                kitchen_sjl.setText("(" + kitchenTemp_str + "/" + kitchenHum_str + ")");
            }
        });
    }
    
    public MqttSubscriber getMqttSubscriberKitchenHumidity(String filter) {
        return(new MqttSubscriber(){
            @Override
            public String getFilter() {
                return(filter);
            }

            @Override
            public void notify(String msg) {
                kitchenHum_str = msg + "°C";
                kitchen_sjl.setText("(" + kitchenTemp_str + "/" + kitchenHum_str + ")");
            }
        });
    }
}
