/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author stephan_wink
 */
public class smallWeatherPanel extends javax.swing.JPanel {

    /**
     * Creates new form smallWeatherPanel
     */
    public smallWeatherPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        day_sjl = new javax.swing.JLabel();
        picture_sjl = new javax.swing.JLabel();
        temp_sjl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(328, 154));
        setMinimumSize(new java.awt.Dimension(328, 154));
        setSize(new java.awt.Dimension(328, 154));

        day_sjl.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        day_sjl.setText("Mittwoch");

        picture_sjl.setBackground(new java.awt.Color(204, 255, 204));
        picture_sjl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon-set/GIF/50x50/chance-storm-n.gif"))); // NOI18N

        temp_sjl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        temp_sjl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        temp_sjl.setText("-10°C/-05°C");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day_sjl)
                    .addComponent(temp_sjl, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(picture_sjl)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(picture_sjl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(day_sjl)
                        .addGap(6, 6, 6)
                        .addComponent(temp_sjl)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel day_sjl;
    private javax.swing.JLabel picture_sjl;
    private javax.swing.JLabel temp_sjl;
    // End of variables declaration//GEN-END:variables

private String day_str;
private String tempMin_str = "0";
private String tempMax_str = "0";
private String iconPath_str;

    public String getDay_str() {
        return day_str;
    }

    public void setDay_str(String newDay_str) {
        this.day_str = newDay_str;
        this.day_sjl.setText(newDay_str);
    }

    public String getTempMin_str() {
        return tempMin_str;
    }

    public void setTempMin_str(String newTempMin_str) {
        this.tempMin_str = newTempMin_str;
        this.temp_sjl.setText("(" + tempMin_str + "°C/" + tempMax_str + "°C)");
    }

    public String getTempMax_str() {
        return tempMax_str;
    }

    public void setTempMax_str(String newTempMax_str) {
        this.tempMax_str = newTempMax_str;
        this.temp_sjl.setText("(" + tempMin_str + "°C/" + tempMax_str + "°C)");
    }

    public String getIconPath_str() {
        return iconPath_str;
    }

    public void setIconPath_str(String iconPath_str) {
        this.iconPath_str = iconPath_str;
        this.picture_sjl.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconPath_str)));
    }
}
