/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import control.MyWeather;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SwingWorker;
import procExe.ExePython;

/**
 *
 * @author winkste
 */
public class weatherPanel extends javax.swing.JPanel {

    private boolean firstTime_bol = true;
    private int waitTime_i = 1000;
    
    /**
     * Creates new form homeTempPanel
     */
    public weatherPanel() {
        initComponents();
        
        new DataCollector().execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pos_sjl = new javax.swing.JLabel();
        time_sjl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        date_sjl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        firstDayPanel_smp = new gui.smallWeatherPanel();
        secondDayPanel_smp = new gui.smallWeatherPanel();
        thirdDayPanel_smp = new gui.smallWeatherPanel();
        todayPanel_bwp = new gui.bigWeatherPanel();

        setMaximumSize(new java.awt.Dimension(788, 377));
        setMinimumSize(new java.awt.Dimension(788, 377));
        setPreferredSize(new java.awt.Dimension(788, 377));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(788, 377));
        jPanel1.setMinimumSize(new java.awt.Dimension(788, 377));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(788, 377));

        pos_sjl.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        pos_sjl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pos_sjl.setText("Celle");

        time_sjl.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        time_sjl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time_sjl.setText("16 : 05");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("extra info");

        date_sjl.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        date_sjl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        date_sjl.setText("27. Jan 2017");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("extra info");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(todayPanel_bwp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(date_sjl, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pos_sjl, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time_sjl, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstDayPanel_smp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondDayPanel_smp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thirdDayPanel_smp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(todayPanel_bwp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pos_sjl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(time_sjl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date_sjl)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstDayPanel_smp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondDayPanel_smp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thirdDayPanel_smp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date_sjl;
    private gui.smallWeatherPanel firstDayPanel_smp;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pos_sjl;
    private gui.smallWeatherPanel secondDayPanel_smp;
    private gui.smallWeatherPanel thirdDayPanel_smp;
    private javax.swing.JLabel time_sjl;
    private gui.bigWeatherPanel todayPanel_bwp;
    // End of variables declaration//GEN-END:variables

    private String lastWeatherSet_str;
    public static long counter = 1;
    private int minCounter_i = 5;
    
    class DataCollector extends SwingWorker<Long, Object>
    {       
        @Override public Long doInBackground()
        {
            try 
            { 
                // update cycle 1 minute
                //Thread.sleep(1000*60); 
                if(firstTime_bol == true)
                {
                    Thread.sleep(waitTime_i);
                    waitTime_i = 1000 * 60 * 1;  // 1mins
                    firstTime_bol = false;
                }
                else
                {
                    Thread.sleep(waitTime_i);
                }
            } catch ( InterruptedException e ) { }
          new DataCollector().execute();
          return (counter++);
        }

        @Override protected void done()
        {
            minCounter_i++;
            try
            {
                // do this every 10 minutes
                if(10 < minCounter_i)
                {
                    lastWeatherSet_str = ExePython.execPython("requestWeather.py");
                    System.out.println(lastWeatherSet_str);
                    MyWeather weather = new MyWeather(lastWeatherSet_str);
                    todayPanel_bwp.setDay_str(weatherPanel.convertDay(weather.getDay0_str()));
                    todayPanel_bwp.setTempMin_str(weather.getDay0MinTemp_str());
                    todayPanel_bwp.setTempMax_str(weather.getDay0MaxTemp_str());
                    todayPanel_bwp.setTemp_str(weather.getDay0ActTemp_str());
                    todayPanel_bwp.setHum_str(weather.getDay0Hum_str());
                    todayPanel_bwp.setIconPath_str(weather.getDay0IconPath_str());

                    firstDayPanel_smp.setDay_str(weatherPanel.convertDay(weather.getDay1_str()));
                    firstDayPanel_smp.setTempMax_str(weather.getDay1MaxTemp_str());
                    firstDayPanel_smp.setTempMin_str(weather.getDay1MinTemp_str());
                    firstDayPanel_smp.setIconPath_str(weather.getDay1IconPath_str());

                    secondDayPanel_smp.setDay_str(weatherPanel.convertDay(weather.getDay2_str()));
                    secondDayPanel_smp.setTempMax_str(weather.getDay2MaxTemp_str());
                    secondDayPanel_smp.setTempMin_str(weather.getDay2MinTemp_str());
                    secondDayPanel_smp.setIconPath_str(weather.getDay2IconPath_str());

                    thirdDayPanel_smp.setDay_str(weatherPanel.convertDay(weather.getDay3_str()));
                    thirdDayPanel_smp.setTempMax_str(weather.getDay3MaxTemp_str());
                    thirdDayPanel_smp.setTempMin_str(weather.getDay3MinTemp_str());
                    thirdDayPanel_smp.setIconPath_str(weather.getDay3IconPath_str());
                    minCounter_i = 0;
                }
                
                // do this every minute
                updateDateTime();

                
                
            }
            catch ( /* InterruptedException, ExecutionException */ Exception e ) { }
        }

        private void updateDateTime() {
            // update date / time information
            Date d = new Date();
            
            SimpleDateFormat sdfmt = new SimpleDateFormat();
            //sdfmt.applyPattern( "EEEE', 'dd. MMMM yyyy HH:mm" );
            //System.out.println(sdfmt.format(d));
            
            //sdfmt = new SimpleDateFormat();
            sdfmt.applyPattern( "dd', 'MMM. yyyy" );
            //System.out.println(sdfmt.format(d));
            date_sjl.setText(sdfmt.format(d));
            
            sdfmt = new SimpleDateFormat();
            sdfmt.applyPattern( "HH:mm" );
            //System.out.println(sdfmt.format(d));
            time_sjl.setText(sdfmt.format(d));
        }       
    }
    
    static public String convertDay(String day_str)
    {
        String newDay_str = "NA";

        if(day_str.equalsIgnoreCase("Mon")){newDay_str = "Montag";}
        else if(day_str.equalsIgnoreCase("Tue")){newDay_str = "Dienstag";}
        else if(day_str.equalsIgnoreCase("Wed")){newDay_str = "Mittwoch";}
        else if(day_str.equalsIgnoreCase("Thu")){newDay_str = "Donnerstag";}
        else if(day_str.equalsIgnoreCase("Fri")){newDay_str = "Freitag";}
        else if(day_str.equalsIgnoreCase("Sat")){newDay_str = "Samstag";}
        else if(day_str.equalsIgnoreCase("Sun")){newDay_str = "Sonntag";}
        else {newDay_str = "NA";}
        return(newDay_str);
    }
}
